In [1]:
import numpy as np
import xarray as xr

In [3]:
data = 283 + 5 * np.random.randn(5, 3, 4)
data

array([[[279.9579901 , 292.16755302, 289.68661949, 286.20930783],
        [278.93908029, 287.16422536, 276.09506009, 285.59942344],
        [292.65927146, 294.99435359, 285.87974248, 283.86224552]],

       [[286.77795185, 289.14429461, 280.51905113, 286.17126765],
        [291.70075556, 275.86252205, 278.71493767, 287.47286814],
        [283.95225485, 289.00741406, 278.26059205, 280.6166002 ]],

       [[291.70905017, 283.77043837, 269.23042672, 281.24921338],
        [278.31615339, 284.43274415, 284.36213741, 282.94149157],
        [285.16675182, 284.27678116, 281.74081643, 283.87896434]],

       [[276.65960301, 278.02535765, 276.25211588, 288.97707971],
        [281.40395552, 282.8284827 , 300.52161251, 281.77519486],
        [289.29844724, 278.1535766 , 293.09297575, 274.883214  ]],

       [[286.69137141, 286.50795413, 280.14766494, 295.22852651],
        [275.84425185, 281.3750694 , 287.53579957, 282.79582179],
        [287.55736804, 282.49034887, 284.52558064, 281.51668321]]])

In [15]:
temp = xr.DataArray(data)
temp

<xarray.DataArray (dim_0: 5, dim_1: 3, dim_2: 4)>
array([[[279.9579901 , 292.16755302, 289.68661949, 286.20930783],
        [278.93908029, 287.16422536, 276.09506009, 285.59942344],
        [292.65927146, 294.99435359, 285.87974248, 283.86224552]],

       [[286.77795185, 289.14429461, 280.51905113, 286.17126765],
        [291.70075556, 275.86252205, 278.71493767, 287.47286814],
        [283.95225485, 289.00741406, 278.26059205, 280.6166002 ]],

       [[291.70905017, 283.77043837, 269.23042672, 281.24921338],
        [278.31615339, 284.43274415, 284.36213741, 282.94149157],
        [285.16675182, 284.27678116, 281.74081643, 283.87896434]],

       [[276.65960301, 278.02535765, 276.25211588, 288.97707971],
        [281.40395552, 282.8284827 , 300.52161251, 281.77519486],
        [289.29844724, 278.1535766 , 293.09297575, 274.883214  ]],

       [[286.69137141, 286.50795413, 280.14766494, 295.22852651],
        [275.84425185, 281.3750694 , 287.53579957, 282.79582179],
        [287.55736804, 282.49034887, 284.52558064, 281.51668321]]])
Dimensions without coordinates: dim_0, dim_1, dim_2

In [17]:
temp = xr.DataArray(data, dims=['time','lat','lon'])
temp

<xarray.DataArray (time: 5, lat: 3, lon: 4)>
array([[[279.9579901 , 292.16755302, 289.68661949, 286.20930783],
        [278.93908029, 287.16422536, 276.09506009, 285.59942344],
        [292.65927146, 294.99435359, 285.87974248, 283.86224552]],

       [[286.77795185, 289.14429461, 280.51905113, 286.17126765],
        [291.70075556, 275.86252205, 278.71493767, 287.47286814],
        [283.95225485, 289.00741406, 278.26059205, 280.6166002 ]],

       [[291.70905017, 283.77043837, 269.23042672, 281.24921338],
        [278.31615339, 284.43274415, 284.36213741, 282.94149157],
        [285.16675182, 284.27678116, 281.74081643, 283.87896434]],

       [[276.65960301, 278.02535765, 276.25211588, 288.97707971],
        [281.40395552, 282.8284827 , 300.52161251, 281.77519486],
        [289.29844724, 278.1535766 , 293.09297575, 274.883214  ]],

       [[286.69137141, 286.50795413, 280.14766494, 295.22852651],
        [275.84425185, 281.3750694 , 287.53579957, 282.79582179],
        [287.55736804, 282.49034887, 284.52558064, 281.51668321]]])
Dimensions without coordinates: time, lat, lon

In [19]:
import pandas as pd
times = pd.date_range('2018-01-01', periods=5)
times

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05'],
              dtype='datetime64[ns]', freq='D')

In [21]:
lons = np.linspace(-120, 60, 4)
lats = np.linspace(25, 55, 3)

In [22]:
temp = xr.DataArray(data, coords=[times, lats, lons], dims=['time','lat','lon'])
temp

<xarray.DataArray (time: 5, lat: 3, lon: 4)>
array([[[279.9579901 , 292.16755302, 289.68661949, 286.20930783],
        [278.93908029, 287.16422536, 276.09506009, 285.59942344],
        [292.65927146, 294.99435359, 285.87974248, 283.86224552]],

       [[286.77795185, 289.14429461, 280.51905113, 286.17126765],
        [291.70075556, 275.86252205, 278.71493767, 287.47286814],
        [283.95225485, 289.00741406, 278.26059205, 280.6166002 ]],

       [[291.70905017, 283.77043837, 269.23042672, 281.24921338],
        [278.31615339, 284.43274415, 284.36213741, 282.94149157],
        [285.16675182, 284.27678116, 281.74081643, 283.87896434]],

       [[276.65960301, 278.02535765, 276.25211588, 288.97707971],
        [281.40395552, 282.8284827 , 300.52161251, 281.77519486],
        [289.29844724, 278.1535766 , 293.09297575, 274.883214  ]],

       [[286.69137141, 286.50795413, 280.14766494, 295.22852651],
        [275.84425185, 281.3750694 , 287.53579957, 282.79582179],
        [287.55736804, 282.49034887, 284.52558064, 281.51668321]]])
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -60.0 0.0 60.0

In [23]:
temp.attrs['units'] = 'kelvin'
temp.attrs['standard_name'] = 'air_temperature'

temp

<xarray.DataArray (time: 5, lat: 3, lon: 4)>
array([[[279.9579901 , 292.16755302, 289.68661949, 286.20930783],
        [278.93908029, 287.16422536, 276.09506009, 285.59942344],
        [292.65927146, 294.99435359, 285.87974248, 283.86224552]],

       [[286.77795185, 289.14429461, 280.51905113, 286.17126765],
        [291.70075556, 275.86252205, 278.71493767, 287.47286814],
        [283.95225485, 289.00741406, 278.26059205, 280.6166002 ]],

       [[291.70905017, 283.77043837, 269.23042672, 281.24921338],
        [278.31615339, 284.43274415, 284.36213741, 282.94149157],
        [285.16675182, 284.27678116, 281.74081643, 283.87896434]],

       [[276.65960301, 278.02535765, 276.25211588, 288.97707971],
        [281.40395552, 282.8284827 , 300.52161251, 281.77519486],
        [289.29844724, 278.1535766 , 293.09297575, 274.883214  ]],

       [[286.69137141, 286.50795413, 280.14766494, 295.22852651],
        [275.84425185, 281.3750694 , 287.53579957, 282.79582179],
        [287.55736804, 282.49034887, 284.52558064, 281.51668321]]])
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -60.0 0.0 60.0
Attributes:
    units:          kelvin
    standard_name:  air_temperature

In [24]:
temp - 273.15

<xarray.DataArray (time: 5, lat: 3, lon: 4)>
array([[[ 6.8079901 , 19.01755302, 16.53661949, 13.05930783],
        [ 5.78908029, 14.01422536,  2.94506009, 12.44942344],
        [19.50927146, 21.84435359, 12.72974248, 10.71224552]],

       [[13.62795185, 15.99429461,  7.36905113, 13.02126765],
        [18.55075556,  2.71252205,  5.56493767, 14.32286814],
        [10.80225485, 15.85741406,  5.11059205,  7.4666002 ]],

       [[18.55905017, 10.62043837, -3.91957328,  8.09921338],
        [ 5.16615339, 11.28274415, 11.21213741,  9.79149157],
        [12.01675182, 11.12678116,  8.59081643, 10.72896434]],

       [[ 3.50960301,  4.87535765,  3.10211588, 15.82707971],
        [ 8.25395552,  9.6784827 , 27.37161251,  8.62519486],
        [16.14844724,  5.0035766 , 19.94297575,  1.733214  ]],

       [[13.54137141, 13.35795413,  6.99766494, 22.07852651],
        [ 2.69425185,  8.2250694 , 14.38579957,  9.64582179],
        [14.40736804,  9.34034887, 11.37558064,  8.36668321]]])
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -60.0 0.0 60.0

In [25]:
from datetime import timedelta
temp.sel(time='2018-01-07', method='nearest', tolerance=timedelta(days=2))

/home/anthony/anaconda3/lib/python3.9/site-packages/xarray/core/indexes.py:234: FutureWarning: Passing method to DatetimeIndex.get_loc is deprecated and will raise in a future version. Use index.get_indexer([item], method=...) instead.
  indexer = self.index.get_loc(


<xarray.DataArray (lat: 3, lon: 4)>
array([[286.69137141, 286.50795413, 280.14766494, 295.22852651],
       [275.84425185, 281.3750694 , 287.53579957, 282.79582179],
       [287.55736804, 282.49034887, 284.52558064, 281.51668321]])
Coordinates:
    time     datetime64[ns] 2018-01-05
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -60.0 0.0 60.0
Attributes:
    units:          kelvin
    standard_name:  air_temperature

In [32]:
temp.interp(lat=40,lon=-105)

/home/anthony/anaconda3/lib/python3.9/site-packages/xarray/core/missing.py:562: FutureWarning: Passing method to Float64Index.get_loc is deprecated and will raise in a future version. Use index.get_indexer([item], method=...) instead.
  imin = index.get_loc(minval, method="nearest")
/home/anthony/anaconda3/lib/python3.9/site-packages/xarray/core/missing.py:563: FutureWarning: Passing method to Float64Index.get_loc is deprecated and will raise in a future version. Use index.get_indexer([item], method=...) instead.
  imax = index.get_loc(maxval, method="nearest")
/home/anthony/anaconda3/lib/python3.9/site-packages/xarray/core/missing.py:562: FutureWarning: Passing method to Float64Index.get_loc is deprecated and will raise in a future version. Use index.get_indexer([item], method=...) instead.
  imin = index.get_loc(minval, method="nearest")
/home/anthony/anaconda3/lib/python3.9/site-packages/xarray/core/missing.py:563: FutureWarning: Passing method to Float64Index.get_loc is deprecated 

<xarray.DataArray (time: 5)>
array([280.99536655, 287.74119718, 279.84530108, 281.76008731,
       277.22695624])
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01 2018-01-02 ... 2018-01-05
    lat      int64 40
    lon      int64 -105
Attributes:
    units:          kelvin
    standard_name:  air_temperature

In [33]:
temp.sel(time=slice('2018-01-01', '2018-01-03'), lon=slice(-110, -70), lat=slice(25, 45))

<xarray.DataArray (time: 3, lat: 2, lon: 0)>
array([], shape=(3, 2, 0), dtype=float64)
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01 2018-01-02 2018-01-03
  * lat      (lat) float64 25.0 40.0
  * lon      (lon) float64 
Attributes:
    units:          kelvin
    standard_name:  air_temperature

In [35]:
temp.loc['2018-01-02']

<xarray.DataArray (lat: 3, lon: 4)>
array([[286.77795185, 289.14429461, 280.51905113, 286.17126765],
       [291.70075556, 275.86252205, 278.71493767, 287.47286814],
       [283.95225485, 289.00741406, 278.26059205, 280.6166002 ]])
Coordinates:
    time     datetime64[ns] 2018-01-02
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -60.0 0.0 60.0
Attributes:
    units:          kelvin
    standard_name:  air_temperature

In [37]:
temp.loc[-110:-70, 25:45,'2018-01-01':'2018-01-03']

TypeError: cannot do slice indexing on DatetimeIndex with these indexers [-110] of type int

In [38]:
ds = xr.open_dataset('../ERA5_sandbox/era5_test1.nc')
ds

<xarray.Dataset>
Dimensions:    (longitude: 41, latitude: 41, level: 2, time: 744)
Coordinates:
  * longitude  (longitude) float32 -91.0 -90.75 -90.5 ... -81.5 -81.25 -81.0
  * latitude   (latitude) float32 17.0 16.75 16.5 16.25 ... 7.75 7.5 7.25 7.0
  * level      (level) int32 1000 850
  * time       (time) datetime64[ns] 2018-07-01 ... 2018-07-31T23:00:00
Data variables:
    u          (time, level, latitude, longitude) float32 ...
    v          (time, level, latitude, longitude) float32 ...
Attributes:
    Conventions:  CF-1.6
    history:      2022-05-25 09:30:37 GMT by grib_to_netcdf-2.24.3: /opt/ecmw...

In [40]:
ds.longitude

<xarray.DataArray 'longitude' (longitude: 41)>
array([-91.  , -90.75, -90.5 , -90.25, -90.  , -89.75, -89.5 , -89.25, -89.  ,
       -88.75, -88.5 , -88.25, -88.  , -87.75, -87.5 , -87.25, -87.  , -86.75,
       -86.5 , -86.25, -86.  , -85.75, -85.5 , -85.25, -85.  , -84.75, -84.5 ,
       -84.25, -84.  , -83.75, -83.5 , -83.25, -83.  , -82.75, -82.5 , -82.25,
       -82.  , -81.75, -81.5 , -81.25, -81.  ], dtype=float32)
Coordinates:
  * longitude  (longitude) float32 -91.0 -90.75 -90.5 ... -81.5 -81.25 -81.0
Attributes:
    units:      degrees_east
    long_name:  longitude

In [41]:
ds['time']

<xarray.DataArray 'time' (time: 744)>
array(['2018-07-01T00:00:00.000000000', '2018-07-01T01:00:00.000000000',
       '2018-07-01T02:00:00.000000000', ..., '2018-07-31T21:00:00.000000000',
       '2018-07-31T22:00:00.000000000', '2018-07-31T23:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 2018-07-01 ... 2018-07-31T23:00:00
Attributes:
    long_name:  time

In [42]:
ds_1000 = ds.sel(level=1000)
ds_1000

<xarray.Dataset>
Dimensions:    (longitude: 41, latitude: 41, time: 744)
Coordinates:
  * longitude  (longitude) float32 -91.0 -90.75 -90.5 ... -81.5 -81.25 -81.0
  * latitude   (latitude) float32 17.0 16.75 16.5 16.25 ... 7.75 7.5 7.25 7.0
    level      int32 1000
  * time       (time) datetime64[ns] 2018-07-01 ... 2018-07-31T23:00:00
Data variables:
    u          (time, latitude, longitude) float32 ...
    v          (time, latitude, longitude) float32 ...
Attributes:
    Conventions:  CF-1.6
    history:      2022-05-25 09:30:37 GMT by grib_to_netcdf-2.24.3: /opt/ecmw...

In [44]:
ds_1000.u

<xarray.DataArray 'u' (time: 744, latitude: 41, longitude: 41)>
[1250664 values with dtype=float32]
Coordinates:
  * longitude  (longitude) float32 -91.0 -90.75 -90.5 ... -81.5 -81.25 -81.0
  * latitude   (latitude) float32 17.0 16.75 16.5 16.25 ... 7.75 7.5 7.25 7.0
    level      int32 1000
  * time       (time) datetime64[ns] 2018-07-01 ... 2018-07-31T23:00:00
Attributes:
    units:          m s**-1
    long_name:      U component of wind
    standard_name:  eastward_wind

In [47]:
v_winds = ds['u']
v_winds.std(dim=['latitude', 'longitude'])

<xarray.DataArray 'u' (time: 744, level: 2)>
array([[3.5793962, 4.281294 ],
       [3.6873271, 4.2627754],
       [3.7605798, 4.2199144],
       ...,
       [3.9481103, 4.1364994],
       [3.6064227, 3.871555 ],
       [3.7849622, 3.991265 ]], dtype=float32)
Coordinates:
  * level    (level) int32 1000 850
  * time     (time) datetime64[ns] 2018-07-01 ... 2018-07-31T23:00:00

In [51]:
co_v_winds = v_winds.sel(latitude=slice(10, 14), longitude=slice(-88,-84), level=slice(1000))
prof = co_v_winds.mean(dim=['latitude', 'longitude'])
prof

<xarray.DataArray 'u' (time: 744, level: 1)>
array([[nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
...
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan]], dtype=float32)
Coordinates:
  * level    (level) int32 1000
  * time     (time) datetime64[ns] 2018-07-01 ... 2018-07-31T23:00:00

In [30]:
help(np.interp)

Help on function interp in module numpy:

interp(x, xp, fp, left=None, right=None, period=None)
    One-dimensional linear interpolation for monotonically increasing sample points.
    
    Returns the one-dimensional piecewise linear interpolant to a function
    with given discrete data points (`xp`, `fp`), evaluated at `x`.
    
    Parameters
    ----------
    x : array_like
        The x-coordinates at which to evaluate the interpolated values.
    
    xp : 1-D sequence of floats
        The x-coordinates of the data points, must be increasing if argument
        `period` is not specified. Otherwise, `xp` is internally sorted after
        normalizing the periodic boundaries with ``xp = xp % period``.
    
    fp : 1-D sequence of float or complex
        The y-coordinates of the data points, same length as `xp`.
    
    left : optional float or complex corresponding to fp
        Value to return for `x < xp[0]`, default is `fp[0]`.
    
    right : optional float or complex co

In [8]:
help(np.random.randn)

Help on built-in function randn:

randn(...) method of numpy.random.mtrand.RandomState instance
    randn(d0, d1, ..., dn)
    
    Return a sample (or samples) from the "standard normal" distribution.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `standard_normal`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    .. note::
        New code should use the ``standard_normal`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    If positive int_like arguments are provided, `randn` generates an array
    of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1. A single float randomly sampled
    from the distribution is returned if no argument is provided.
 